### ISSUE TITLE
request.body.data returns a string without double quotes for Content-Type: application/json

### ISSUE THREAD

**Issue by aferust** [trikko/serverino#13]
Hi Andrea,

I hope you are doing well.

this curl call:
curl --header "Content-Type: application/json" --request POST --data '{"email":"ferhat@somemail.com","passwordHash":"1234"}' "http://localhost:8080/newuser"

In the endpoint function, request.body.data is '{email:ferhat,password:1234}'. So I cannot use parseJSON(request.body.data) even I strip outer single quotes. Am I doing something wrong?

**Comment by aferust** [comment]
oh my stupid windows shell, this works:

curl --header "Content-Type: application/json" --request POST --data '{\"email\":\"ferhat\",\"password\":\"1234\"}' "http://localhost:8080/newuser

anyway thank you!

**Comment by trikko** [comment]
No problem, happy to see some testing 👍🏻
