### ISSUE TITLE
v0.7.0 fails to compile.

### ISSUE THREAD

**Issue by IGIAG** [trikko/serverino#18]
When using freshly installed v0.7.0 i get the following compilation errors:
`Performing "debug" build using /usr/bin/ldc2 for x86_64.
serverino 0.7.0: target for configuration "lib" is up to date.
matura-api ~master: building configuration "application"...
../.dub/packages/serverino-0.7.0/serverino/source/serverino/daemon.d(491,61): Error: no property `release` for type `std.socket.Socket`
../.dub/packages/serverino-0.7.0/serverino/source/serverino/main.d(187,59): Error: template instance `serverino.daemon.Daemon.wake!(app)` error instantiating
../.dub/packages/serverino-0.7.0/serverino/source/serverino/main.d(158,14):        instantiated from here: `wakeServerino!(app)`
/usr/bin/ldc2 failed with exit code 1.`
The error dissapears when chenged to v0.6.5

**Comment by trikko** [comment]
Hi @IGIAG. Probably you have a old version of dmd. Socket.release() was added in a recent version of dlang. Could you check which version are you running?

**Comment by trikko** [comment]
Ok, released a new minor version. If you're using a old compiler, websockets are disabled and a warning is shown.

You can also build your project without websockets using the config `disable_websockets`
