### ISSUE TITLE
Cannot Use IPV6

### ISSUE THREAD

**Issue by duoduo70** [trikko/serverino#2]
config.d -> struct ServerinoConfig -> enum ListenerProtocol
should be changed to ***static***

**Comment by trikko** [comment]
Hey there! What was the problem? If it's not a bug, maybe I can improve docs.

**Comment by duoduo70** [comment]
Hello!
I want to use IPv6. I noticed template of method "config.d -> struct ServerinoConfig -> addListener" is "ListenerProtocol".
But this enum is not static. I do not know how can use it.
Can you help me? Thank you very well!

**Comment by trikko** [comment]
The right syntax is:
```yourconfig.addListener!(ServerinoConfig.ListenerProtocol.IPV6)("localhost", 8080)```

But there's a regression (just a missing import) that I've fixed right now. So please upgrade your dependencies with:
```dub upgrade```

Thank you for your report!
