### ISSUE TITLE
Compilation error when building serverino on Raspberry Pi 4

### ISSUE THREAD

**Issue by o3o** [trikko/serverino#22]
## Description

When attempting to compile `serverino` on a Raspberry Pi 4, the following error occurs:

```
[mluser@mq serverino]$ dub build
Performing "debug" build using /usr/bin/ldc2 for arm, arm_hardfloat.
serverino 0.7.10: building configuration "lib"...
source/serverino/communicator.d(475,24): Error: cannot implicitly convert expression `this.file.size() + cast(ulong)headers.length` of type `ulong` to `uint`
source/serverino/interfaces.d(1427,89): Deprecation: integral promotion not done for `~MASK`, use '-preview=intpromote' switch or `~cast(int)(MASK)`
source/serverino/interfaces.d(1433,28): Deprecation: integral promotion not done for `~MASK`, use '-preview=intpromote' switch or `~cast(int)(MASK)`
source/serverino/interfaces.d(1443,28): Deprecation: integral promotion not done for `~MASK`, use '-preview=intpromote' switch or `~cast(int)(MASK)`
```

## Environment
- Hardware: Raspberry Pi 4
- Operating System: Linux 5.10.60-1-ARCH #1 SMP Sat Aug 21 14:56:38 UTC 2021 armv7l GNU/Linux
- Compiler: LDC - the LLVM D compiler (1.27.1) based on DMD v2.097.2 and LLVM 12.0.1
 
Thank you

**Comment by trikko** [comment]
Grazie Orfeo :)

Domanda: perché usi la versione a 32 bit?

**Comment by o3o** [comment]
Ciao Andrea, innanzi lasciami  complimentarmi per l'ottimo lavoro che hai fatto: e' veloce, leggero, ben documentato ed (cosa piu' importante) elegantemente scritto.
La raspberry comunica con dei dispositivi a microprocessore e purtroppo ne abbiamo centinaia in giro e devo mantenere la compatibilita'. La prossima versione uscira' a 64bit con server Rest implementato tramite il mitico Serverino.
Grazie ancora e buona serata
