### ISSUE TITLE
Incorrect Query String Handling in request.get.read

### ISSUE THREAD

**Issue by o3o** [trikko/serverino#24]
When there are multiple elements in the query string, request.get.read does not return the correct values. For example:
```
      unittest {
         string[string] output;
         enum S =  "/api/v1/sequences?per_page=2&page=8";
         RequestImpl req;
         req.parseArgsString(S, output);
         assert(output.length == 2);

         //assert(("per_page" in output) != null); // fail
         assert(("page" in output) != null);
         //assert(o["per_page"] == "2"); // fail
         //assert(o["page"] == "8");// fail

         assert(("/api/v1/sequences?per_page" in output) != null); // pass
 
      }

```
I'm not sure if this behavior is intended, but [here](https://github.com/o3o/serverino-o3o/blob/a7fa868f5cc015e358abdac7f4c67b7b1dc35742/source/serverino/interfaces.d#L795) is a simple solution you can consider.

**Comment by trikko** [comment]
Whaaaaat? This is a huge regression

**Comment by trikko** [comment]
Wait a sec: https://test.andreafontana.it/api/v1/sequences?per_page=2&page=8 this show the params correctly. So what am I missing?

**Comment by trikko** [comment]
Hmm, `parseArgsString` only accepts query strings (without the starting '?'), as you can see here https://github.com/trikko/serverino/blob/05c89790669fa12716918373bf7fdbfff8b34b78/source/serverino/worker.d#L473

So, is there a way to trigger this bug from user code?

**Comment by o3o** [comment]
I think I could be doing something wrong because I haven’t fully understood how to properly use `request.get`. Here’s a [simplified example](https://github.com/o3o/issue24/tree/master) of how I’m using it

**Comment by trikko** [comment]
"problemino" 😆 works fine for me. Are you sure you're typing the url correctly? Which urls are you testing?

**Comment by trikko** [comment]
[Video del 09-10-2024 13:07:12.webm](https://github.com/user-attachments/assets/e914b79d-8c63-4c71-b187-96d0f79ac62f)

**Comment by o3o** [comment]
I found the issue. If I use a browser, everything works as expected, just like in your example. 

However, when I use curl, as written in `get_sequences_p.sh`, it doesn't work. The solution is to include the path in quotes! (`curl -X GET "localhost:8282/api/v2/sequences?page=1&per_page=2"`)

Apologies for the false alarm, and thanks again for the great software you've written.

**Comment by trikko** [comment]
No problem. Thanks for the attention, it's always helpful to have another pair of eyes watching out for potential bugs. Better to resolve a false alarm than to ignore a real one.
