### ISSUE TITLE
The part that can write is too small

### ISSUE THREAD

**Issue by duoduo70** [trikko/serverino#6]
I want to write a big html file. But I found that it can write up to 32768 bytes.

How to reproduce:
```d
output ~= new char[200_000];
```

The html file is only 32768 bytes.

**Comment by trikko** [comment]
There's a limit on data sending using output ~=. 

For big file you should write them somewhere on disk and then serve them using ```output.serveFile()```

See: https://serverino.dpldocs.info/serverino.interfaces.Output.serveFile.html

**Comment by duoduo70** [comment]
No change.

reproduce:
```d
std.file.write("test.html", new char[200_000]);
output.serveFile("test.html");
```
and save file to "temp.html".
test.html size: 200000 bytes.
temp.html size: 32768 bytes.

**Comment by trikko** [comment]
Nice catch.

**Comment by trikko** [comment]
Hi there, I can't reproduce this bug (but I found another one, investigating this one).

For example this download a 200k file:

```d
module app;

import serverino;
import std;

mixin ServerinoMain;

void file(Request request, Output output)
{
        std.file.write("test.html", new char[200_000]);
        output.serveFile("test.html");
}
```

Does it work for you? Which system?

**Comment by duoduo70** [comment]
Wow! It work!
I dont know why it dont work on another project...
thank you very much.
I can investigate further.

**Comment by duoduo70** [comment]
And I am sorry

**Comment by trikko** [comment]
Don't worry, you're welcome. I fixed a bug investigating your issue 😀

**Comment by p0nce** [comment]
I'm hitting the exact same bug.

On Windows, it is indeed solve by writing to a file and using serveFile
but on Linux + LDC 1.28 + nginx forwaring, only the first 32kb seems to be sent.
<img width="741" alt="image" src="https://github.com/trikko/serverino/assets/1067485/c4f1c912-6757-4aee-be0a-e82c4c00f862">

**Comment by trikko** [comment]
Using serveFile, you mean? It should not.

**Comment by p0nce** [comment]
I solved it, my problem was bad nginx configuration.

Here is the commit that made it work:
<img width="505" alt="image" src="https://github.com/trikko/serverino/assets/1067485/eec91a82-f156-4da7-903a-e6c7ed851dc9">

So I think the issue was that "Connection" header.

**Comment by trikko** [comment]
You scared me, I thought there was a bad bug!

**Comment by p0nce** [comment]
Still I think writing more than 32kb using Output.write should at least fail loudly, since everyone has to come read this bug report else.

**Comment by trikko** [comment]
You're right. And they're wasting time of course. I'm going to fix it with a big warning on the log.
